on: push
jobs:
  meu_primeiro_job:
    runs-on: ubuntu-latest
             # ubuntu-24.4, windows-lastest, windows-2022
             # Xcode iOs macOS Swift macos-lastest macos-14 
    steps:
      - run: echo "Olá, Fatec!"
