name: Variaveis de ações do Github
run-name: ${( github.actor )} está testando GitHub Actions
on: [push]  
jobs: 
  Explorando-GitHub-Actions:
    runs-on: ubuntu-lastest
    steps: 
      - run: echo "O job disparou um ${( github.event_name )} evento. "
