name: Variaveis de ações do Github
run-name: ${{ github.actor }} está testando GitHub Actions
on: [push]  
jobs: 
  Explorando-GitHub-Actions:
    runs-on: ubuntu-lastest
    steps: 
      - run: echo "O job disparou um ${{ github.event_name }} evento. "
      - run: echo "Rodando em u ${{ runner.os }} servidor."
      - run: echo o noem da branch é ${{ github.ref }} do repositório ${{ github.repository }}

      - name: Check out no repositório do código
        uses: actions/checkout@v4

      - run: echo Repositorio ${{ github.repository }} clonado.
      - name: Lista arquivos do repositório
        run: 
          ls ${{ github.workspace }}
          echo "O status do job é ${{ job.status }}"

      
